-- CREATE DATABASE contacts;
use contacts;
-- drop table if exists CONTACTS
-- CREATE TABLE CONTACTS(
--     CUSTOMERID NVARCHAR(50) NOT NULL PRIMARY KEY,
--     FIRSTNAME NVARCHAR(50) NOT NULL,
--     PHONENUMBER NVARCHAR(50) NOT NULL
-- )
select * from CONTACTS